"""Paths, defaults and JSON state helpers.

Other modules read these as `config.NAME` at call time (never
`from .config import NAME`) so tests can point them at a temporary directory.
"""

import json
from pathlib import Path

DEFAULTS = {
    "evening_temp": 3400,
    "late_temp": 2700,
    "late_after": 180,
    "off_time": "07:00",
}

HOME = Path.home()
CONF = HOME / ".config/hypr/hyprsunset.conf"
CONF_BACKUP = HOME / ".config/hypr/hyprsunset.conf.pre-nightlight"
MARKER = "# Generated by the io.github.agkrishnendu.nightlight Omarchy plugin"
WEATHER_LOC = HOME / ".local/state/omarchy/settings/weather.json"
STATE = HOME / ".local/state/nightlight-schedule"
CACHE = STATE / "coords.json"
OVERRIDE = STATE / "override.json"
SCHEDULE_STATE = STATE / "schedule.json"


def read_json(path):
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data))
